### ISSUE TITLE
Call Delegate methods should default to `YES`, not `NO`

### ISSUE THREAD

**Issue by orta** [sammcewan/WYPopoverController#42]
Here: https://github.com/sammcewan/WYPopoverController/blob/master/WYPopoverController/WYPopoverController.m#L2780

I'll be doing this in my fork, ( which alas has things that shouldn't really be in master ) but I think the `YES` is typical behaviour for PopoverControllers.

**Comment by nemphys** [comment]
Totally agree, delegate methods should *always* be called.

**Comment by vitalys** [comment]
`WYPopoverController` mimics behavior of `UIPopoverController`, so `popoverControllerDidDismissPopover:` won't be called if you dismiss popover using `dismissPopoverAnimated:` method
