### ISSUE TITLE
Popover hides instantly

### ISSUE THREAD

**Issue by citruz** [sammcewan/WYPopoverController#49]
Hi,
I want to use WYPopoverController in my iOS 8 app using the following code:
```
UIViewController *vc = [self.storyboard instantiateViewControllerWithIdentifier:@"selectMapViewController"];
    
WYPopoverController *popoverController = [[WYPopoverController alloc] initWithContentViewController:vc];
popoverController.delegate = self;
popoverController presentPopoverFromBarButtonItem:sender permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];
```
When I tap the connected button, I can see the Popover View fading in, but it is disappearing instantly.
What am I doing wrong?

Cheers

**Comment by rolleric** [comment]
Could it be that it is deallocated because there is no strong reference to it? Try storing the popoverController as a "strong" property.

**Comment by citruz** [comment]
Great, thanks for the hint!
